Repository neuropsychology/NeuroKit, pull requests merged in 2020-06, with the labels that each got.

#233 Exploring Github CI
  .github/workflows/tests.yml
  .travis.yml
  docs/conf.py
  neurokit2/emg/emg_amplitude.py
  neurokit2/rsp/rsp_amplitude.py
  neurokit2/rsp/rsp_peaks.py
  setup.py
  tox.ini
Labels: size/L

#234 Update rsp_findpeaks.py
  AUTHORS.rst
  neurokit2/rsp/rsp_findpeaks.py
Labels: size/XS

#246 documentation action
  .github/workflows/figures.yml
  .github/workflows/graphs.yml
Labels: size/L

#251 Update eda.ipynb
  docs/examples/eda.ipynb
Labels: size/XS

#252 Fixed potential bug in hrv_nonlinear.py
  AUTHORS.rst
  neurokit2/hrv/hrv_nonlinear.py
Labels: size/XS

#256 Migrate codecov to gh action
  .coveragerc
  pytest.ini
  tox.ini
Labels: size/M

#259 Improve release drafter action
  .github/release-drafter-config.yml
  .github/workflows/release-drafter.yml
Labels: size/M

#260 [feature] EOG processing: add blink detection method and cleaning methods
  neurokit2/eog/__init__.py
  neurokit2/eog/eog_clean.py
  neurokit2/eog/eog_findpeaks.py
  neurokit2/eog/eog_peaks.py
Labels: size/L

#263 [feature] SSA-based Single-channel decomposition methods
  .github/CONTRIBUTING.rst
  .github/workflows/style.yml
  docs/conf.py
  neurokit2/__init__.py
  neurokit2/benchmark/__init__.py
  neurokit2/benchmark/benchmark_ecg.py
  neurokit2/benchmark/benchmark_utils.py
  neurokit2/complexity/complexity_dimension.py
  neurokit2/complexity/complexity_embedding.py
  neurokit2/complexity/complexity_simulate.py
  neurokit2/complexity/utils.py
  neurokit2/ecg/ecg_clean.py
  neurokit2/ecg/ecg_delineate.py
  neurokit2/ecg/ecg_findpeaks.py
  neurokit2/ecg/ecg_rsa.py
  neurokit2/eda/eda_intervalrelated.py
  neurokit2/eda/eda_phasic.py
  neurokit2/emg/emg_intervalrelated.py
  neurokit2/rsp/rsp_simulate.py
  neurokit2/signal/__init__.py
  neurokit2/signal/signal_changepoints.py
  neurokit2/signal/signal_decompose.py
  neurokit2/signal/signal_filter.py
  neurokit2/signal/signal_fixpeaks.py
  neurokit2/signal/signal_formatpeaks.py
  neurokit2/signal/signal_recompose.py
  neurokit2/stats/__init__.py
  neurokit2/stats/mutual_information.py
Labels: size/L

#264 [fix] hrv_nonlinear: changed SD2/SD1 ratio of Poincaré to SD1/SD2
  neurokit2/hrv/hrv_nonlinear.py
  tests/tests_ecg.py
  tests/tests_hrv.py
Labels: Breaking change :radioactive:, size/XS

#262 [CI] update test workflows
  .github/workflows/style.yml
  .github/workflows/tests.yml
  codecov.yml
  neurokit2/eog/eog_process.py
  setup.py
  tasks.py
  tests/tests.py
  tests/tests_bio.py
  tests/tests_complexity.py
  tests/tests_data.py
  tests/tests_ecg.py
  tests/tests_ecg_delineate.py
  tests/tests_eda.py
  tests/tests_eeg.py
  tests/tests_emg.py
  tests/tests_eog.py
  tests/tests_events.py
  tests/tests_hrv.py
  tests/tests_ppg.py
  tests/tests_rsp.py
  tests/tests_signal.py
  tests/tests_signal_fixpeaks.py
  tests/tests_stats.py
Labels: size/XXL

#273 [feature] add new method for signal_psd()
  .github/workflows/style.yml
  neurokit2/signal/signal_psd.py
  tests/tests_ecg.py
Labels: size/L

#280 Attempt to fix failing CI
  .github/workflows/checks.yml
  docs/readme/README_examples.py
Labels: size/XS

#276 [API] API of signal_period() and signal_rate()
  neurokit2/signal/signal_fixpeaks.py
  neurokit2/signal/signal_period.py
  neurokit2/signal/signal_rate.py
Labels: Breaking change :radioactive:, size/M

#286 [features] Improve signal_plot()
  neurokit2/signal/signal_plot.py
Labels: size/S

#277 [docs] README improvements
  .github/workflows/checks.yml
  README.rst
  docs/readme/README_examples.py
  docs/readme/README_psd.png
  neurokit2/signal/signal_psd.py
Labels: size/M

#288 [feature] PPG process pipeline
  README.rst
  docs/readme/README_ppg.png
  neurokit2/ppg/__init__.py
  neurokit2/ppg/ppg_plot.py
  neurokit2/ppg/ppg_process.py
Labels: size/L

#283 [features] Add `nk.eog_plot()`
  README.rst
  docs/readme/README_eog.png
  docs/readme/README_examples.py
  neurokit2/eog/__init__.py
  neurokit2/eog/eog_plot.py
  tests/tests_eog.py
Labels: size/M

#291 [docs] Use of mdinclude directive to add .md files to sphinx docs
  AUTHORS.rst
  benchmarks/ecg_preprocessing/README.md
  docs/benchmarks/ecg_preprocessing.rst
  docs/conf.py
  docs/environment.yml
Labels: size/M

#294 [CI] update style workflow
  .github/workflows/style.yml
  neurokit2/signal/signal_interpolate.py
Labels: size/S

#298 [docs] Add HRV example
  docs/examples/hrv.ipynb
Labels: size/M

#297 [feature] plot blinks in eog_plot
  docs/readme/README_eog.png
  docs/readme/README_examples.py
  neurokit2/eog/eog_plot.py
Labels: size/M
