Repository neuropsychology/NeuroKit, pull requests merged in 2020-08, with the labels that each got.

#345 [Fix] #344 with corresponding test
  neurokit2/hrv/hrv_nonlinear.py
  tests/tests_hrv.py
Labels: size/S

#331 [Feature] EEG microstates analysis (basics)
  .github/workflows/style.yml
  .gitignore
  README.rst
  data/rs_eeg_texas/README.md
  docs/contributing/first_contribution.rst
  neurokit2/__init__.py
  neurokit2/complexity/__init__.py
  neurokit2/complexity/transition_matrix.py
  neurokit2/data/data.py
  neurokit2/eda/eda_sympathetic.py
  neurokit2/eeg/__init__.py
  neurokit2/eeg/eeg_badchannels.py
  neurokit2/eeg/eeg_diss.py
  neurokit2/eeg/eeg_gfp.py
  neurokit2/eeg/eeg_rereference.py
  neurokit2/eeg/mne_channel_add.py
  neurokit2/eeg/mne_data.py
  neurokit2/eeg/mne_to_df.py
  neurokit2/emg/emg_activation.py
  neurokit2/hrv/hrv_frequency.py
  neurokit2/microstates/__init__.py
  neurokit2/microstates/microstates_classify.py
  neurokit2/microstates/microstates_clean.py
  neurokit2/microstates/microstates_complexity.py
  neurokit2/microstates/microstates_dynamic.py
  neurokit2/microstates/microstates_findnumber.py
  neurokit2/microstates/microstates_peaks.py
  neurokit2/microstates/microstates_plot.py
  neurokit2/microstates/microstates_segment.py
  neurokit2/microstates/microstates_static.py
  neurokit2/misc/__init__.py
  neurokit2/misc/find_groups.py
  neurokit2/misc/replace.py
  neurokit2/signal/signal_filter.py
  neurokit2/signal/signal_psd.py
  neurokit2/stats/__init__.py
  neurokit2/stats/cluster.py
  neurokit2/stats/cluster_findnumber.py
  neurokit2/stats/cluster_quality.py
  neurokit2/stats/distance.py
  neurokit2/stats/mad.py
  scripts/eeg_microstates.py
  studies/erp_gam/README.Rmd
  studies/erp_gam/README.md
  studies/erp_gam/bibliography.bib
  studies/erp_gam/figures/fig1.png
  studies/erp_gam/figures/unnamed-chunk-12-1.png
  studies/erp_gam/figures/unnamed-chunk-14-1.png
  studies/microstates_howmany/script.py
  tests/tests_microstates.py
Labels: size/XXL

#346 [Fix] Code Climate
  neurokit2/complexity/transition_matrix.py
  neurokit2/eda/eda_sympathetic.py
  neurokit2/eeg/eeg_diss.py
  neurokit2/eeg/eeg_rereference.py
  neurokit2/eeg/mne_data.py
  neurokit2/hrv/hrv_rsa.py
  neurokit2/microstates/microstates_findnumber.py
  neurokit2/microstates/microstates_segment.py
  neurokit2/misc/replace.py
  neurokit2/rsp/__init__.py
  neurokit2/rsp/rsp_rate.py
  neurokit2/signal/signal_timefrequency.py
  neurokit2/stats/cluster.py
  neurokit2/stats/cluster_quality.py
Labels: size/L

#348 Update AUTHORS.rst
  AUTHORS.rst
Labels: size/XS

#349 [Fix] Review microstate implementations
  neurokit2/microstates/microstates_segment.py
  neurokit2/stats/cluster.py
  neurokit2/stats/cluster_quality.py
Labels: size/L
