Repository neuropsychology/NeuroKit, pull requests merged in 2020-10, with the labels that each got.

#371 input check for series when non-default index is set.
  neurokit2/eda/eda_process.py
Labels: size/XS

#347 0.0.41
  .binder/requirements.txt
  .github/CODE_OF_CONDUCT.md
  .github/workflows/style.yml
  .gitignore
  .travis.yml
  AUTHORS.rst
  docs/conf.py
  docs/environment.yml
  docs/readme/README_popularity.png
  neurokit2/__init__.py
  neurokit2/ecg/ecg_analyze.py
  neurokit2/ecg/ecg_phase.py
  neurokit2/eda/eda_analyze.py
  neurokit2/eda/eda_intervalrelated.py
  neurokit2/eda/eda_process.py
  neurokit2/emg/emg_analyze.py
  neurokit2/eog/eog_analyze.py
  neurokit2/eog/eog_clean.py
  neurokit2/eog/eog_findpeaks.py
  neurokit2/eog/eog_simulate.py
  neurokit2/microstates/microstates_classify.py
  neurokit2/microstates/microstates_dynamic.py
  neurokit2/microstates/microstates_findnumber.py
  neurokit2/microstates/microstates_plot.py
  neurokit2/microstates/microstates_segment.py
  neurokit2/signal/signal_decompose.py
  neurokit2/signal/signal_fixpeaks.py
  neurokit2/signal/signal_formatpeaks.py
  neurokit2/stats/cluster.py
  neurokit2/stats/cluster_quality.py
  neurokit2/stats/rescale.py
  paper/bibliography.bib
  paper/figures/figure.pptx
  paper/figures/nk_architecture.jpg
  paper/figures/nk_architecture.pdf
  paper/figures/nk_architecture.png
  paper/figures/nk_architecture.tif
  paper/manuscript_v3.Rmd
  paper/manuscript_v3.out
  paper/manuscript_v3.pdf
  paper/manuscript_v4.Rmd
  paper/manuscript_v4.pdf
  studies/erp_gam/README.Rmd
  studies/erp_gam/README.md
  studies/erp_gam/figures/unnamed-chunk-10-1.png
  studies/erp_gam/figures/unnamed-chunk-12-1.png
  studies/erp_gam/figures/unnamed-chunk-14-1.png
  studies/erp_gam/figures/unnamed-chunk-15-1.png
  studies/erp_gam/figures/unnamed-chunk-16-1.png
  tests/tests_eda.py
  tox.ini
Labels: patch, size/XXL

#374 [Fix] Pygment style for jupyter
  docs/environment.yml
Labels: size/XS

#372 signal_sanitize() added, when non-default index for pandas series cau…
  neurokit2/ecg/ecg_process.py
  neurokit2/eda/eda_process.py
  neurokit2/emg/emg_process.py
  neurokit2/rsp/rsp_process.py
  neurokit2/signal/__init__.py
  neurokit2/signal/signal_sanitize.py
Labels: size/M
