Repository neuropsychology/NeuroKit, pull requests merged in 2020-07, with the labels that each got.

#299 [feature] Add EOG into bio_* functions
  neurokit2/bio/bio_analyze.py
  neurokit2/bio/bio_process.py
  neurokit2/eog/__init__.py
  neurokit2/eog/eog_analyze.py
  neurokit2/eog/eog_eventrelated.py
  neurokit2/eog/eog_intervalrelated.py
  tests/tests_eog.py
Labels: size/L

#303 ecg_analyze should pass sampling_rate to ecg_intervalrelated call
  AUTHORS.rst
  neurokit2/ecg/ecg_analyze.py
Labels: size/XS

#305 ecg_intervalrelated test case, fixed contributors spacing
  AUTHORS.rst
  tests/tests_ecg.py
Labels: size/XS

#307 [Fix] ppg simulate
  neurokit2/ppg/ppg_simulate.py
  tests/tests_ppg.py
Labels: size/L

#308 [Change] ecg_rsa becomes hrv_rsa
  neurokit2/bio/bio_analyze.py
  neurokit2/bio/bio_process.py
  neurokit2/ecg/__init__.py
  neurokit2/hrv/__init__.py
  neurokit2/hrv/hrv_rsa.py
Labels: size/M

#311 [Feature] add version() function to easily retrieve system info
  .github/ISSUE_TEMPLATE/bug_report.md
  neurokit2/__init__.py
Labels: size/M

#318 typofix_docs_examples_ecg
  docs/examples/ecg_delineate.ipynb
Labels: size/XS

#314 [Fix] ecg_delineate CWT mode crash when no consecutive tp peaks found
  AUTHORS.rst
  neurokit2/ecg/ecg_delineate.py
  tests/tests_ecg_delineate.py
Labels: size/L

#300 [Fix] PSD Methods
  .travis.yml
  data/ecg_1000hz.csv
  data/ecg_3000hz.csv
  neurokit2/eda/__init__.py
  neurokit2/eda/eda_sympathetic.py
  neurokit2/hrv/hrv_frequency.py
  neurokit2/hrv/hrv_utils.py
  neurokit2/signal/signal_power.py
  neurokit2/signal/signal_psd.py
  setup.py
Labels: size/M

#320 [Improvement] Refactor all printed NeuroKit warnings into warning control
  neurokit2/ecg/ecg_eventrelated.py
  neurokit2/ecg/ecg_plot.py
  neurokit2/eda/eda_autocor.py
  neurokit2/eda/eda_changepoints.py
  neurokit2/eda/eda_eventrelated.py
  neurokit2/eeg/mne_channel_extract.py
  neurokit2/emg/emg_eventrelated.py
  neurokit2/emg/emg_plot.py
  neurokit2/eog/eog_eventrelated.py
  neurokit2/eog/eog_plot.py
  neurokit2/epochs/eventrelated_utils.py
  neurokit2/events/events_find.py
  neurokit2/hrv/hrv_frequency.py
  neurokit2/hrv/hrv_rsa.py
  neurokit2/misc/__init__.py
  neurokit2/misc/warnings.py
  neurokit2/ppg/ppg_plot.py
  neurokit2/rsp/rsp_eventrelated.py
  neurokit2/rsp/rsp_rrv.py
  neurokit2/signal/signal_distort.py
  neurokit2/signal/signal_filter.py
  neurokit2/signal/signal_period.py
  neurokit2/signal/signal_power.py
  neurokit2/signal/signal_psd.py
  neurokit2/signal/signal_simulate.py
  tests/tests_ecg.py
  tests/tests_eda.py
  tests/tests_emg.py
  tests/tests_eog.py
  tests/tests_events.py
  tests/tests_hrv.py
  tests/tests_rsp.py
  tests/tests_signal.py
Labels: size/XL

#334 respiration sampling rate issue
  AUTHORS.rst
  neurokit2/rsp/rsp_analyze.py
  neurokit2/rsp/rsp_rrv.py
Labels: size/S

#325 [Feature] New EDA and EMG peak and onset detection methods
  neurokit2/eda/eda_findpeaks.py
  neurokit2/eda/eda_peaks.py
  neurokit2/emg/emg_activation.py
Labels: size/L

#337 [Fix] corrected 'heart' with 'respiratory' in docstring
  neurokit2/rsp/rsp_intervalrelated.py
Labels: size/XS

#327 [feature] Time-frequency methods
  neurokit2/ecg/ecg_clean.py
  neurokit2/ecg/ecg_rsp.py
  neurokit2/ecg/ecg_simulate.py
  neurokit2/eda/eda_sympathetic.py
  neurokit2/hrv/hrv_frequency.py
  neurokit2/signal/signal_psd.py
  neurokit2/signal/signal_timefrequency.py
  tests/tests_signal.py
Labels: size/XL

#341 [Feature] Add new respiration rate methods
  neurokit2/rsp/__init__.py
  neurokit2/rsp/rsp_rate.py
Labels: size/L

#336 [Feature] Dynamic RSA
  neurokit2/bio/bio_analyze.py
  neurokit2/eda/eda_sympathetic.py
  neurokit2/hrv/hrv_rsa.py
  neurokit2/rsp/rsp_rate.py
  neurokit2/signal/signal_timefrequency.py
  tests/tests_hrv.py
Labels: size/L

#343 [Feature] add new ECG peak detection method
  neurokit2/ecg/ecg_findpeaks.py
Labels: size/M
