Repository neuropsychology/NeuroKit, pull requests merged in 2021-11, with the labels that each got.

#567 Complexity hotfixes
  neurokit2/complexity/complexity_lempelziv.py
  neurokit2/complexity/complexity_lyapunov.py
  neurokit2/complexity/entropy_range.py
  neurokit2/complexity/entropy_sample.py
  neurokit2/complexity/optim_complexity_tolerance.py
  studies/complexity_benchmark/data.csv
  studies/complexity_benchmark/make_data.py
Labels: size/XXL

#571 Noise simulation
  .github/workflows/tests.yml
  neurokit2/complexity/complexity.py
  neurokit2/complexity/fractal_correlation.py
  neurokit2/complexity/fractal_nld.py
  neurokit2/complexity/fractal_psdslope.py
  neurokit2/complexity/optim_complexity_dimension.py
  neurokit2/data/write_csv.py
  neurokit2/hrv/hrv_nonlinear.py
  neurokit2/hrv/hrv_rsa.py
  neurokit2/signal/__init__.py
  neurokit2/signal/signal_noise.py
  studies/complexity_benchmark/1_ComputationTime.py
  studies/complexity_benchmark/2_Correlation.py
  studies/complexity_benchmark/README.Rmd
  studies/complexity_benchmark/README.md
  studies/complexity_benchmark/data_ComputationTime.csv
  studies/complexity_benchmark/data_Correlations.csv
  studies/complexity_benchmark/figures/unnamed-chunk-3-1.png
  studies/complexity_benchmark/figures/unnamed-chunk-4-1.png
  studies/complexity_benchmark/figures/unnamed-chunk-5-1.png
Labels: size/XL

#575 Remove unused args in hrv_time
  neurokit2/hrv/hrv_time.py
Labels: size/XS

#573 eeg_power()
  .github/workflows/checks.yml
  .github/workflows/tests.yml
  neurokit2/complexity/TODO_fractal_capacity.py
  neurokit2/complexity/complexity.py
  neurokit2/complexity/complexity_lempelziv.py
  neurokit2/complexity/complexity_lyapunov.py
  neurokit2/complexity/fractal_dfa.py
  neurokit2/complexity/fractal_psdslope.py
  neurokit2/eda/eda_sympathetic.py
  neurokit2/eeg/__init__.py
  neurokit2/eeg/eeg_gfp.py
  neurokit2/eeg/eeg_power.py
  neurokit2/eeg/mne_data.py
  neurokit2/eeg/mne_to_df.py
  neurokit2/hrv/hrv_frequency.py
  neurokit2/signal/signal_power.py
  neurokit2/signal/signal_psd.py
  setup.py
  studies/complexity_benchmark/2_Correlation.py
  studies/complexity_benchmark/README.Rmd
  studies/complexity_benchmark/README.md
  studies/complexity_benchmark/data_Correlations.csv
  studies/complexity_benchmark/figures/unnamed-chunk-5-1.png
  studies/complexity_benchmark/figures/unnamed-chunk-6-1.png
Labels: size/XXL

#574 No warning for signal_psd: default min_freq
  docs/examples/eeg_power.ipynb
  neurokit2/complexity/entropy_multiscale.py
  neurokit2/eda/eda_sympathetic.py
  neurokit2/eeg/eeg_power.py
  neurokit2/eeg/mne_channel_extract.py
  neurokit2/eeg/mne_crop.py
  neurokit2/eeg/utils.py
  neurokit2/signal/signal_power.py
  neurokit2/signal/signal_psd.py
  tests/tests_hrv.py
  tests/tests_rsp.py
  tests/tests_signal.py
Labels: size/L

#577 Rerun examples and tutorials
  docs/examples/custom.ipynb
  docs/examples/ecg_delineate.ipynb
  docs/examples/eda.ipynb
  docs/examples/edr.ipynb
  docs/examples/eog.ipynb
  docs/examples/epochs_create.ipynb
  docs/examples/eventrelated.ipynb
  docs/examples/fit_function.ipynb
  docs/examples/heartbeats.ipynb
  docs/examples/hrv.ipynb
  docs/examples/intervalrelated.ipynb
  docs/examples/rrv.ipynb
  docs/examples/simulation.ipynb
  neurokit2/complexity/fractal_dfa.py
  neurokit2/signal/signal_psd.py
Labels: size/XXL
