Repository neuropsychology/NeuroKit, pull requests merged in 2021-03, with the labels that each got.

#415 [Feature] Updated Error Bar Request
  neurokit2/hrv/hrv.py
  neurokit2/hrv/hrv_time.py
  neurokit2/stats/summary.py
Labels: size/S

#423 Optimize _ecg_findpeaks_MWA
  neurokit2/ecg/ecg_findpeaks.py
  tests/tests_ecg_findpeaks_MWA.py
Labels: size/M

#424 Fixed issue #421: ragged nested sequences
  neurokit2/eda/eda_findpeaks.py
Labels: size/XS

#432 Boxcar
  neurokit2/ecg/ecg_findpeaks.py
  neurokit2/signal/signal_smooth.py
  neurokit2/signal/signal_timefrequency.py
  tests/tests_ecg_findpeaks_MWA.py
  tests/tests_signal.py
Labels: size/L
