Repository neuropsychology/NeuroKit, pull requests merged in 2021-08, with the labels that each got.

#486 docs typo: pamtompkins -> pantompkins
  neurokit2/ecg/ecg_findpeaks.py
  neurokit2/ecg/ecg_peaks.py
Labels: size/XS

#493 Fractal and multifractal measures
  AUTHORS.rst
  neurokit2/complexity/__init__.py
  neurokit2/complexity/fractal_dfa.py
Labels: size/XL

#494 convert intervals to peaks
  NEWS.rst
  neurokit2/misc/__init__.py
  neurokit2/misc/intervals_to_peaks.py
Labels: size/M

#490 DFA fix from LRydin's fork
  AUTHORS.rst
  neurokit2/complexity/__init__.py
  neurokit2/complexity/fractal_dfa.py
  neurokit2/hrv/hrv_nonlinear.py
  neurokit2/rsp/rsp_rrv.py
  tests/tests_complexity.py
  tests/tests_ecg.py
  tests/tests_hrv.py
Labels: size/XL

#501 Fix geometric indices of HRV
  neurokit2/hrv/hrv_time.py
Labels: size/M

#502 Fix download error when downloading `mne` datasets
  NEWS.rst
  neurokit2/eeg/mne_data.py
Labels: size/S

#499 More complexity indices
  neurokit2/complexity/__init__.py
  neurokit2/complexity/complexity_lempelziv.py
  neurokit2/complexity/fractal_higuchi.py
  neurokit2/complexity/fractal_katz.py
Labels: size/L

#503 Add new hrv indices into hrv_time and hrv_nonlinear
  neurokit2/bio/bio_analyze.py
  neurokit2/complexity/fractal_higuchi.py
  neurokit2/ecg/ecg_intervalrelated.py
  neurokit2/hrv/hrv_nonlinear.py
  neurokit2/hrv/hrv_time.py
  neurokit2/ppg/ppg_intervalrelated.py
  tests/tests_ecg.py
Labels: size/L

#487 dev
  AUTHORS.rst
  CITATION.cff
  NEWS.rst
  README.rst
  docs/readme/README_popularity.png
  neurokit2/__init__.py
  neurokit2/bio/bio_analyze.py
  neurokit2/complexity/__init__.py
  neurokit2/complexity/complexity_lempelziv.py
  neurokit2/complexity/fractal_dfa.py
  neurokit2/complexity/fractal_higuchi.py
  neurokit2/complexity/fractal_katz.py
  neurokit2/ecg/ecg_findpeaks.py
  neurokit2/ecg/ecg_intervalrelated.py
  neurokit2/ecg/ecg_peaks.py
  neurokit2/eeg/mne_data.py
  neurokit2/hrv/hrv_nonlinear.py
  neurokit2/hrv/hrv_time.py
  neurokit2/misc/__init__.py
  neurokit2/misc/intervals_to_peaks.py
  neurokit2/ppg/ppg_intervalrelated.py
  neurokit2/rsp/rsp_rrv.py
  tests/tests_complexity.py
  tests/tests_ecg.py
  tests/tests_hrv.py
Labels: size/XXL

#504 0.1.4.1
  CITATION.cff
  NEWS.rst
  neurokit2/__init__.py
  neurokit2/complexity/__init__.py
  neurokit2/complexity/complexity_optimize.py
  neurokit2/complexity/fractal_dfa.py
  neurokit2/complexity/fractal_higuchi.py
  neurokit2/complexity/utils.py
  neurokit2/hrv/hrv_nonlinear.py
  neurokit2/signal/__init__.py
  studies/hrv_structure/make_data.py
Labels: size/L
