Repository neuropsychology/NeuroKit, pull requests merged in 2021-09, with the labels that each got.

#521 Format `complexity` outputs
  NEWS.rst
  neurokit2/complexity/complexity_lempelziv.py
  neurokit2/complexity/complexity_optimize.py
  neurokit2/complexity/complexity_r.py
  neurokit2/complexity/entropy_approximate.py
  neurokit2/complexity/entropy_fuzzy.py
  neurokit2/complexity/entropy_multiscale.py
  neurokit2/complexity/entropy_sample.py
  neurokit2/complexity/entropy_shannon.py
  neurokit2/complexity/fractal_correlation.py
  neurokit2/complexity/fractal_dfa.py
  neurokit2/complexity/fractal_higuchi.py
  neurokit2/complexity/fractal_katz.py
  neurokit2/hrv/hrv_nonlinear.py
  neurokit2/rsp/rsp_rrv.py
  setup.py
  tests/tests_complexity.py
Labels: size/L

#526 Sanitize emg offset indices
  NEWS.rst
  neurokit2/emg/emg_activation.py
Labels: size/S

#530 [Fix] _interpolate_big method from signal_fixpeaks method
  neurokit2/signal/signal_fixpeaks.py
Labels: size/XS

#537 hrv_time() does not throw an ValueError for input array with constant…
  neurokit2/hrv/hrv_time.py
Labels: size/XS

#525 Sanitize HRV outputs
  NEWS.rst
  neurokit2/complexity/fractal_dfa.py
  neurokit2/complexity/fractal_higuchi.py
  neurokit2/hrv/hrv_time.py
Labels: size/S

#539 Update AUTHORS.rst
  AUTHORS.rst
Labels: size/XS

#538 [Fix] Signal_fixpeaks_neurokit
  neurokit2/signal/signal_fixpeaks.py
Labels: size/XS

#535 Distinguish intervals from peaks in `hrv_*()`
  NEWS.rst
  neurokit2/hrv/hrv_utils.py
Labels: size/S

#536 Add and clarify RSP features
  neurokit2/rsp/rsp_eventrelated.py
  neurokit2/rsp/rsp_findpeaks.py
  neurokit2/rsp/rsp_fixpeaks.py
  neurokit2/rsp/rsp_peaks.py
  neurokit2/rsp/rsp_plot.py
  neurokit2/rsp/rsp_process.py
  neurokit2/rsp/rsp_rrv.py
Labels: size/M

#550 Compute respiration rate based on troughs
  NEWS.rst
  neurokit2/rsp/rsp_amplitude.py
  neurokit2/rsp/rsp_peaks.py
  neurokit2/rsp/rsp_process.py
  neurokit2/rsp/rsp_rate.py
  neurokit2/rsp/rsp_rrv.py
  tests/tests_rsp.py
Labels: size/M

#551 Functions to account for more `mne` features
  NEWS.rst
  neurokit2/eeg/__init__.py
  neurokit2/eeg/eeg_badchannels.py
  neurokit2/eeg/mne_channel_add.py
  neurokit2/eeg/mne_channel_extract.py
  neurokit2/eeg/mne_crop.py
  neurokit2/eeg/mne_to_df.py
  neurokit2/eog/__init__.py
  neurokit2/eog/eog_findpeaks.py
  neurokit2/eog/eog_peaks.py
  neurokit2/epochs/epochs_plot.py
Labels: size/L
