Repository neuropsychology/NeuroKit, pull requests merged in 2021-07, with the labels that each got.

#478 Bug fix ecg_findpeaks_rodrigues
  neurokit2/ecg/ecg_findpeaks.py
Labels: size/XS

#483 Add and fix ecg_delineate features
  NEWS.rst
  neurokit2/ecg/ecg_delineate.py
Labels: size/L

#455 0.1.3
  .github/release-drafter-config.yml
  .github/workflows/tests.yml
  NEWS.rst
  README.rst
  docs/examples/ecg_delineate.ipynb
  docs/examples/hrv.ipynb
  neurokit2/__init__.py
  neurokit2/bio/bio_analyze.py
  neurokit2/complexity/fractal_dfa.py
  neurokit2/ecg/ecg_clean.py
  neurokit2/ecg/ecg_delineate.py
  neurokit2/ecg/ecg_eventrelated.py
  neurokit2/ecg/ecg_findpeaks.py
  neurokit2/ecg/ecg_intervalrelated.py
  neurokit2/ecg/ecg_quality.py
  neurokit2/eda/eda_clean.py
  neurokit2/eda/eda_intervalrelated.py
  neurokit2/emg/emg_clean.py
  neurokit2/emg/emg_eventrelated.py
  neurokit2/emg/emg_intervalrelated.py
  neurokit2/eog/eog_analyze.py
  neurokit2/eog/eog_clean.py
  neurokit2/eog/eog_eventrelated.py
  neurokit2/eog/eog_intervalrelated.py
  neurokit2/epochs/epochs_create.py
  neurokit2/epochs/eventrelated_utils.py
  neurokit2/hrv/hrv.py
  neurokit2/ppg/ppg_clean.py
  neurokit2/ppg/ppg_eventrelated.py
  neurokit2/ppg/ppg_intervalrelated.py
  neurokit2/rsp/rsp_clean.py
  neurokit2/rsp/rsp_eventrelated.py
  neurokit2/rsp/rsp_intervalrelated.py
  setup.py
  tests/tests_ecg.py
  tests/tests_eda.py
  tests/tests_emg.py
  tests/tests_eog.py
Labels: size/XL
