Repository neuropsychology/NeuroKit, pull requests merged in 2021-06, with the labels that each got.

#460 A parameter lost in `eog_plot`
  README.rst
Labels: size/XS

#461 fix epochs_end from duration of events
  neurokit2/epochs/epochs_create.py
Labels: size/XS

#468 Add labelling to subepochs
  NEWS.rst
  neurokit2/ecg/ecg_intervalrelated.py
  neurokit2/eda/eda_intervalrelated.py
  neurokit2/emg/emg_intervalrelated.py
  neurokit2/eog/eog_intervalrelated.py
  neurokit2/ppg/ppg_intervalrelated.py
  neurokit2/rsp/rsp_intervalrelated.py
  tests/tests_ecg.py
  tests/tests_eda.py
  tests/tests_emg.py
  tests/tests_eog.py
Labels: size/M

#471 add sd features in `eventrelated` functions
  NEWS.rst
  neurokit2/bio/bio_analyze.py
  neurokit2/ecg/ecg_eventrelated.py
  neurokit2/emg/emg_eventrelated.py
  neurokit2/eog/eog_analyze.py
  neurokit2/eog/eog_eventrelated.py
  neurokit2/epochs/eventrelated_utils.py
  neurokit2/ppg/ppg_eventrelated.py
  neurokit2/rsp/rsp_eventrelated.py
  tests/tests_emg.py
Labels: size/M

#470 clean missing data and sanitize epochs column types
  NEWS.rst
  neurokit2/ecg/ecg_clean.py
  neurokit2/eda/eda_clean.py
  neurokit2/emg/emg_clean.py
  neurokit2/eog/eog_clean.py
  neurokit2/epochs/epochs_create.py
  neurokit2/ppg/ppg_clean.py
  neurokit2/rsp/rsp_clean.py
Labels: size/L
