Repository neuropsychology/NeuroKit, pull requests merged in 2022-04, with the labels that each got.

#630 [Fix] hrv_frequency(): changes in frequency bands correctly propagate
  neurokit2/hrv/hrv_frequency.py
Labels: size/S

#635 [Breaking] Linear and Quadratic Trends indices are now based on raw polynomials (and other fit_* changes)
  neurokit2/epochs/eventrelated_utils.py
  neurokit2/ppg/ppg_eventrelated.py
  neurokit2/signal/signal_detrend.py
  neurokit2/signal/signal_smooth.py
  neurokit2/stats/fit_loess.py
  neurokit2/stats/fit_mixture.py
  neurokit2/stats/fit_polynomial.py
  tests/tests_stats.py
Labels: size/L

#638 signal_fixpeaks() allow kwargs
  neurokit2/signal/signal_fixpeaks.py
Labels: size/M
