Repository neuropsychology/NeuroKit, pull requests merged in 2022-02, with the labels that each got.

#607 [Change] promac parameters exposition / doc update
  .idea/NeuroKit.iml
  .idea/misc.xml
  .idea/workspace.xml
  neurokit2/ecg/ecg_findpeaks.py
  neurokit2/ecg/ecg_peaks.py
Labels: size/L

#612 Replace ba output with sos for ECG filters and determine initial conditions
  .gitignore
  neurokit2/ecg/ecg_clean.py
  neurokit2/ecg/ecg_findpeaks.py
  neurokit2/epochs/epochs_create.py
  neurokit2/stats/distance.py
Labels: size/M

#579 0.1.6
  .github/workflows/checks.yml
  .github/workflows/release.yml
  .github/workflows/style.yml
  .github/workflows/tests.yml
  .gitignore
  .idea/NeuroKit.iml
  .idea/misc.xml
  .idea/workspace.xml
  CITATION.cff
  NEWS.rst
  README.rst
  neurokit2/__init__.py
  neurokit2/bio/bio_analyze.py
  neurokit2/complexity/__init__.py
  neurokit2/complexity/complexity.py
  neurokit2/complexity/complexity_attractor.py
  neurokit2/complexity/complexity_embedding.py
  neurokit2/complexity/complexity_hurst.py
  neurokit2/complexity/complexity_lyapunov.py
  neurokit2/complexity/complexity_recurrence.py
  neurokit2/complexity/complexity_rqa.py
  neurokit2/complexity/complexity_simulate.py
  neurokit2/complexity/entropy_coalition.py
  neurokit2/complexity/entropy_cumulative_residual.py
  neurokit2/complexity/fractal_correlation.py
  neurokit2/complexity/fractal_higuchi.py
  neurokit2/complexity/optim_complexity_delay.py
  neurokit2/complexity/optim_complexity_dimension.py
  neurokit2/complexity/optim_complexity_k.py
  neurokit2/complexity/optim_complexity_tolerance.py
  neurokit2/complexity/utils.py
  neurokit2/data/data.py
  neurokit2/data/read_bitalino.py
  neurokit2/ecg/ecg_clean.py
  neurokit2/ecg/ecg_delineate.py
  neurokit2/ecg/ecg_findpeaks.py
  neurokit2/ecg/ecg_peaks.py
  neurokit2/eeg/eeg_1f.py
  neurokit2/eeg/eeg_rereference.py
  neurokit2/eeg/eeg_source.py
  neurokit2/epochs/epochs_create.py
  neurokit2/events/events_find.py
  neurokit2/misc/expspace.py
  neurokit2/misc/parallel_run.py
  neurokit2/ppg/ppg_findpeaks.py
  neurokit2/signal/signal_decompose.py
  neurokit2/signal/signal_filter.py
  neurokit2/signal/signal_fixpeaks.py
  neurokit2/signal/signal_formatpeaks.py
  neurokit2/signal/signal_noise.py
  neurokit2/signal/signal_plot.py
  neurokit2/signal/signal_psd.py
  neurokit2/signal/signal_rate.py
  neurokit2/signal/signal_sanitize.py
  neurokit2/stats/distance.py
  setup.py
  studies/complexity_benchmark/1_ComputationTime.py
  studies/complexity_benchmark/README.Rmd
  studies/complexity_benchmark/data_ComputationTime.csv
  tests/tests_eeg.py
Labels: size/XXL
