Repository neuropsychology/NeuroKit, pull requests merged in 2022-10, with the labels that each got.

#716 [Feature] ECG inversion
  docs/functions/ecg.rst
  neurokit2/ecg/__init__.py
  neurokit2/ecg/ecg_invert.py
  neurokit2/ecg/ecg_peaks.py
  neurokit2/ecg/ecg_quality.py
  tests/tests_ecg.py
Labels: size/L

#707 [Feature] Report describing methods in PPG process
  neurokit2/misc/report.py
  neurokit2/ppg/__init__.py
  neurokit2/ppg/ppg_clean.py
  neurokit2/ppg/ppg_findpeaks.py
  neurokit2/ppg/ppg_intervalrelated.py
  neurokit2/ppg/ppg_methods.py
  neurokit2/ppg/ppg_plot.py
  neurokit2/ppg/ppg_process.py
  neurokit2/ppg/ppg_report.py
  neurokit2/ppg/ppg_simulate.py
  setup.py
  tests/tests_ppg.py
Labels: size/XL

#727 nk.signal_interpolate – Bugfix
  .gitignore
  .idea/NeuroKit.iml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/other.xml
  .idea/vcs.xml
  .idea/workspace.xml
  neurokit2/signal/signal_interpolate.py
Labels: size/L

#720 [Feature] adjust HRV functions for missing intervals
  neurokit2/hrv/hrv.py
  neurokit2/hrv/hrv_frequency.py
  neurokit2/hrv/hrv_nonlinear.py
  neurokit2/hrv/hrv_rqa.py
  neurokit2/hrv/hrv_rsa.py
  neurokit2/hrv/hrv_time.py
  neurokit2/hrv/hrv_utils.py
  neurokit2/hrv/intervals_process.py
  neurokit2/hrv/intervals_to_peaks.py
  neurokit2/hrv/intervals_utils.py
  tests/tests_hrv.py
Labels: size/L

#731 [Fix] ECG delineator peak index
  neurokit2/ecg/ecg_delineate.py
  neurokit2/signal/signal_formatpeaks.py
Labels: size/L

#732 [Fix] Detection of missing interbeat intervals
  neurokit2/hrv/intervals_utils.py
  tests/tests_hrv.py
Labels: size/M

#730 [Fix] defaults detrend locreg
  neurokit2/hrv/intervals_process.py
  neurokit2/signal/signal_detrend.py
Labels: size/M

#735 [Feature] read_video() function read video files into array (mp4)
  neurokit2/data/__init__.py
  neurokit2/data/read_video.py
Labels: size/M

#737 fix read_bitalino
  neurokit2/data/read_bitalino.py
Labels: size/S

#738 [fix] fix _signal_findpeaks_distances (#733)
  neurokit2/signal/signal_findpeaks.py
Labels: size/S
