Repository neuropsychology/NeuroKit, pull requests merged in 2022-11, with the labels that each got.

#736 [Feature] Webcam video processing for remote physiology (rPPG, ...) (EXPLORATORY)
  docs/functions/data.rst
  docs/functions/index.rst
  docs/functions/misc.rst
  docs/functions/video.rst
  neurokit2/__init__.py
  neurokit2/data/read_bitalino.py
  neurokit2/data/read_video.py
  neurokit2/misc/__init__.py
  neurokit2/misc/progress_bar.py
  neurokit2/signal/signal_interpolate.py
  neurokit2/signal/signal_rate.py
  neurokit2/video/__init__.py
  neurokit2/video/video_blinks.py
  neurokit2/video/video_face.py
  neurokit2/video/video_plot.py
  neurokit2/video/video_ppg.py
  neurokit2/video/video_skin.py
Labels: size/XL

#739 [Example] Add microstates analysis example
  docs/examples/eeg_microstates/eeg_microstates.ipynb
  docs/examples/index.rst
  neurokit2/markov/transition_matrix.py
  neurokit2/microstates/microstates_clean.py
  neurokit2/microstates/microstates_complexity.py
  neurokit2/microstates/microstates_dynamic.py
  neurokit2/microstates/microstates_findnumber.py
  neurokit2/microstates/microstates_peaks.py
  neurokit2/microstates/microstates_segment.py
  neurokit2/microstates/microstates_static.py
Labels: size/XXL

#743 [Docs] Add example for EEG complexity analysis
  docs/examples/eeg_complexity/eeg_complexity.ipynb
  neurokit2/complexity/entropy_svd.py
  neurokit2/complexity/fractal_katz.py
Labels: size/XL

#745 [Feature] ECG R-Peak detection using visibility graphs
  .github/workflows/docs-build.yml
  .github/workflows/docs-check.yml
  AUTHORS.rst
  neurokit2/ecg/ecg_clean.py
  neurokit2/ecg/ecg_findpeaks.py
  neurokit2/ecg/ecg_peaks.py
  setup.py
Labels: size/L

#746 [Feature] Compute RSP cycle symmetry features + new amplitude method
  docs/functions/rsp.rst
  docs/img/cole2019.png
  neurokit2/rsp/__init__.py
  neurokit2/rsp/rsp_amplitude.py
  neurokit2/rsp/rsp_eventrelated.py
  neurokit2/rsp/rsp_intervalrelated.py
  neurokit2/rsp/rsp_phase.py
  neurokit2/rsp/rsp_plot.py
  neurokit2/rsp/rsp_process.py
  neurokit2/rsp/rsp_rrv.py
  neurokit2/rsp/rsp_rvt.py
  neurokit2/rsp/rsp_symmetry.py
  tests/tests_rsp.py
Labels: size/XL

#747 [docs] window size for locreg detrending
  neurokit2/signal/signal_detrend.py
  studies/ecg_benchmark/README.md
  studies/ecg_benchmark/make_data.py
Labels: size/S

#755 [Feature] add rsp_methods (basis for rsp reports)
  neurokit2/misc/report.py
  neurokit2/ppg/ppg_methods.py
  neurokit2/rsp/__init__.py
  neurokit2/rsp/rsp_methods.py
  neurokit2/rsp/rsp_process.py
  neurokit2/rsp/rsp_rvt.py
Labels: size/L
