Repository neuropsychology/NeuroKit, pull requests merged in 2022-03, with the labels that each got.

#617 Pylint subtle formatting fixes
  neurokit2/hrv/hrv_nonlinear.py
  neurokit2/hrv/hrv_time.py
  neurokit2/microstates/microstates_classify.py
  neurokit2/microstates/microstates_findnumber.py
  neurokit2/microstates/microstates_plot.py
  neurokit2/signal/signal_power.py
Labels: size/M

#624 Fix complexity_tolerance using recurrence method
  neurokit2/complexity/optim_complexity_tolerance.py
Labels: size/XS

#625 [New Feature]: Multichannel ECG Simulation
  README.rst
  docs/studies/ecg_generating_12_leads.rst
  docs/studies/index.rst
  neurokit2/ecg/__init__.py
  neurokit2/ecg/ecg_simulate.py
  neurokit2/eeg/eeg_rereference.py
  neurokit2/eeg/mne_data.py
  neurokit2/signal/signal_distort.py
  studies/ecg_generating_12_leads/3D.png
  studies/ecg_generating_12_leads/ECG12_abnormal.png
  studies/ecg_generating_12_leads/ECG12_normal.png
  studies/ecg_generating_12_leads/README.md
  studies/ecg_generating_12_leads/script.py
  studies/ecg_generating_12_leads/table.png
  tests/tests_eog.py
  tests/tests_signal.py
Labels: size/XL

#627 [Feature] add min, max, 80th & 20th percentiles as HRV features
  AUTHORS.rst
  NEWS.rst
  neurokit2/hrv/hrv_time.py
Labels: size/S

#633 [Breaking] Remove subepoch_rate argument in bio_analyze
  neurokit2/bio/bio_analyze.py
  neurokit2/ecg/ecg_analyze.py
  neurokit2/ecg/ecg_eventrelated.py
  neurokit2/epochs/eventrelated_utils.py
  neurokit2/rsp/rsp_analyze.py
  neurokit2/rsp/rsp_eventrelated.py
Labels: size/L

#631 [Fix] Avoid duplicated input sanitization in eda_process
  neurokit2/eda/eda_process.py
Labels: size/XS
