Repository neuropsychology/NeuroKit, pull requests merged in 2022-08, with the labels that each got.

#688 [Feature] Add Harrison RVT
  AUTHORS.rst
  docs/functions/rsp.rst
  neurokit2/rsp/__init__.py
  neurokit2/rsp/rsp_rvt.py
  tests/tests_rsp.py
Labels: size/L

#691 [Fix] Added detected rpeaks to ecg_process
  neurokit2/ecg/ecg_process.py
Labels: size/S

#683 [Feature] MFDFA: allow for q=0
  neurokit2/complexity/fractal_dfa.py
  neurokit2/misc/find_knee.py
  tests/tests_complexity.py
Labels: size/L

#679 [Fix] Calculation of number of NaNs in signal_fixpeaks()
  AUTHORS.rst
  neurokit2/signal/signal_fixpeaks.py
Labels: size/L

#695 [Feature] Added Birn and Power RVT method.
  neurokit2/rsp/rsp_clean.py
  neurokit2/rsp/rsp_findpeaks.py
  neurokit2/rsp/rsp_peaks.py
  neurokit2/rsp/rsp_rvt.py
  tests/tests_ecg.py
  tests/tests_rsp.py
  tests/tests_stats.py
Labels: size/L

#680 [Feature] Option to change interpolation rate of interbeat intervals for HRV frequency
  neurokit2/hrv/hrv_frequency.py
  neurokit2/hrv/hrv_utils.py
Labels: size/M

#666 [Feature] Modify signal_interpolate for input with NaNs and extrapolation
  NEWS.rst
  neurokit2/signal/signal_interpolate.py
Labels: size/L
