Repository neuropsychology/NeuroKit, pull requests merged in 2022-09, with the labels that each got.

#699 [Docs] Fix documentation of RMSSD
  neurokit2/hrv/hrv_time.py
Labels: size/XS

#697 [Fix] eda_peak(): Change peak detection from differentiation signal to phasic signal
  AUTHORS.rst
  neurokit2/eda/eda_findpeaks.py
  tests/tests_eda.py
Labels: size/M

#698 [Docs] Fix documentation of various HRV features
  neurokit2/complexity/entropy_multiscale.py
  neurokit2/complexity/entropy_shannon.py
  neurokit2/complexity/fractal_correlation.py
  neurokit2/complexity/fractal_dfa.py
  neurokit2/hrv/hrv_frequency.py
  neurokit2/hrv/hrv_nonlinear.py
  neurokit2/hrv/hrv_time.py
Labels: size/S

#702 [Breaking] `martinez2003` method for ECG peak detection renamed `martines2004`
  neurokit2/ecg/ecg_findpeaks.py
  neurokit2/ecg/ecg_peaks.py
  tests/tests_ecg.py
Labels: size/M

#706 [Feature] epochs_average(): compute grand average of epochs
  docs/functions/epochs.rst
  neurokit2/epochs/__init__.py
  neurokit2/epochs/epochs_average.py
  neurokit2/epochs/epochs_plot.py
Labels: size/M

#709 [Fix] use signal_filter() in ecg_clean() so that certain methods do not fail with low sampling rate
  neurokit2/ecg/ecg_clean.py
  neurokit2/signal/signal_filter.py
Labels: size/M

#710 [Feature] R-R intervals and associated timestamps as input to HRV functions
  neurokit2/hrv/__init__.py
  neurokit2/hrv/hrv.py
  neurokit2/hrv/hrv_frequency.py
  neurokit2/hrv/hrv_nonlinear.py
  neurokit2/hrv/hrv_rqa.py
  neurokit2/hrv/hrv_rsa.py
  neurokit2/hrv/hrv_time.py
  neurokit2/hrv/hrv_utils.py
  neurokit2/hrv/intervals_preprocess.py
  neurokit2/hrv/intervals_to_peaks.py
  neurokit2/hrv/intervals_utils.py
  neurokit2/misc/__init__.py
  neurokit2/misc/intervals_to_peaks.py
  tests/tests_hrv.py
Labels: size/XL

#713 [Docs] Typo fix in complexity_dimension() docstring
  neurokit2/complexity/optim_complexity_dimension.py
Labels: size/M

#715 [Breaking] entropy_multiscale(): default dimension is now 3 instead of 2
  neurokit2/complexity/entropy_multiscale.py
Labels: size/S

#712 [Feature] use lombscargle PSD method without interpolation
  neurokit2/hrv/hrv_frequency.py
  neurokit2/hrv/intervals_process.py
  neurokit2/hrv/intervals_utils.py
  neurokit2/signal/signal_psd.py
Labels: size/L
