Repository neuropsychology/NeuroKit, pull requests merged in 2023-07, with the labels that each got.

#852 [Fix] typo docstring eda process
  neurokit2/eda/eda_process.py
Labels: size/XS

#841 [Feature] EMG report
  neurokit2/emg/emg_clean.py
  neurokit2/emg/emg_methods.py
  neurokit2/emg/emg_plot.py
  neurokit2/emg/emg_process.py
  neurokit2/misc/report.py
  neurokit2/ppg/ppg_clean.py
  neurokit2/ppg/ppg_methods.py
  neurokit2/ppg/ppg_process.py
  neurokit2/rsp/rsp_methods.py
  tests/tests_emg.py
Labels: size/L

#849 [Breaking] ecg_clean(): update biosppy method
  neurokit2/ecg/ecg_clean.py
  neurokit2/events/events_find.py
  tests/tests_ecg.py
Labels: size/L

#861 [Fix] version sklearn valid_metrics
  neurokit2/complexity/utils.py
  tests/tests_complexity.py
Labels: size/S

#855 [Feature] HRV: Add SD/RMSSD index (Sollers, 2007)
  neurokit2/hrv/hrv_time.py
  neurokit2/signal/signal_period.py
Labels: size/M

#862 Fix/docs asyncio warning
  .github/workflows/docs-build.yml
  .github/workflows/docs-check.yml
  docs/conf.py
Labels: size/S

#814 0.2.5
  .codeclimate.yml
  .github/workflows/docs-build.yml
  .github/workflows/docs-check.yml
  docs/conf.py
  docs/functions/signal.rst
  neurokit2/__init__.py
  neurokit2/complexity/complexity.py
  neurokit2/complexity/fractal_tmf.py
  neurokit2/complexity/optim_complexity_tolerance.py
  neurokit2/complexity/utils.py
  neurokit2/complexity/utils_fractal_mandelbrot.py
  neurokit2/ecg/ecg_clean.py
  neurokit2/ecg/ecg_delineate.py
  neurokit2/ecg/ecg_intervalrelated.py
  neurokit2/ecg/ecg_process.py
  neurokit2/ecg/ecg_quality.py
  neurokit2/eda/eda_process.py
  neurokit2/eeg/mne_channel_extract.py
  neurokit2/emg/emg_clean.py
  neurokit2/emg/emg_methods.py
  neurokit2/emg/emg_plot.py
  neurokit2/emg/emg_process.py
  neurokit2/epochs/eventrelated_utils.py
  neurokit2/events/events_find.py
  neurokit2/hrv/hrv_frequency.py
  neurokit2/hrv/hrv_nonlinear.py
  neurokit2/hrv/hrv_time.py
  neurokit2/hrv/intervals_process.py
  neurokit2/hrv/intervals_to_peaks.py
  neurokit2/hrv/intervals_utils.py
  neurokit2/misc/report.py
  neurokit2/ppg/ppg_clean.py
  neurokit2/ppg/ppg_findpeaks.py
  neurokit2/ppg/ppg_intervalrelated.py
  neurokit2/ppg/ppg_methods.py
  neurokit2/ppg/ppg_process.py
  neurokit2/ppg/ppg_simulate.py
  neurokit2/rsp/rsp_intervalrelated.py
  neurokit2/rsp/rsp_methods.py
  neurokit2/rsp/rsp_process.py
  neurokit2/signal/__init__.py
  neurokit2/signal/signal_fillmissing.py
  neurokit2/signal/signal_filter.py
  neurokit2/signal/signal_interpolate.py
  neurokit2/signal/signal_period.py
  neurokit2/signal/signal_plot.py
  setup.py
  tests/tests_complexity.py
  tests/tests_ecg.py
  tests/tests_eda.py
  tests/tests_emg.py
  tests/tests_ppg.py
  tests/tests_signal.py
Labels: size/XXL

#868 [FIX] KeyError in _eventrelated_addinfo
  neurokit2/epochs/eventrelated_utils.py
Labels: size/XS
