Repository neuropsychology/NeuroKit, pull requests merged in 2023-08, with the labels that each got.

#871 [Docs] ecg_process: improve documentation and readability
  neurokit2/ecg/ecg_process.py
Labels: size/M

#881 [Feature] add random_state to complexity_symbolize
  neurokit2/complexity/utils_complexity_symbolize.py
Labels: size/S

#886 [Docs] Minor Update README.rst
  README.rst
Labels: size/M

#882 [Feature] download zip
  data/fantasia/download_fantasia.py
  data/lemon/download_lemon.py
  data/mit_arrhythmia/download_mit_arrhythmia.py
  neurokit2/data/__init__.py
  neurokit2/data/data.py
  neurokit2/data/database.py
Labels: size/L

#873 [Feature] Respiratory Amplitude Variability (RAV)
  .github/workflows/tests.yml
  neurokit2/rsp/__init__.py
  neurokit2/rsp/rsp_intervalrelated.py
  neurokit2/rsp/rsp_rav.py
  tests/tests_rsp.py
Labels: size/L

#883 [Feature] PPG plots improvements
  docs/functions/ppg.rst
  neurokit2/ecg/ecg_peaks.py
  neurokit2/ecg/ecg_plot.py
  neurokit2/ecg/ecg_segment.py
  neurokit2/hrv/hrv_rsa.py
  neurokit2/ppg/__init__.py
  neurokit2/ppg/ppg_findpeaks.py
  neurokit2/ppg/ppg_peaks.py
  neurokit2/ppg/ppg_plot.py
  neurokit2/ppg/ppg_process.py
  neurokit2/ppg/ppg_segment.py
  neurokit2/signal/signal_rate.py
  tests/tests_bio.py
  tests/tests_ecg.py
  tests/tests_eda.py
Labels: size/XL

#889 [Breaking] for *_plot() and ecg_fixpeaks(method="neurokit")
  .github/workflows/checks.yml
  .github/workflows/releasePR.yml
  README.rst
  docs/readme/README_ecg.png
  docs/readme/README_eda.png
  docs/readme/README_emg.png
  docs/readme/README_eog.png
  docs/readme/README_examples.py
  docs/readme/README_ppg.png
  docs/readme/README_rsp.png
  docs/readme/README_simulation.png
  neurokit2/ecg/ecg_clean.py
  neurokit2/ecg/ecg_peaks.py
  neurokit2/ecg/ecg_phase.py
  neurokit2/ecg/ecg_plot.py
  neurokit2/ecg/ecg_process.py
  neurokit2/ecg/ecg_segment.py
  neurokit2/eda/eda_plot.py
  neurokit2/eda/eda_process.py
  neurokit2/emg/emg_plot.py
  neurokit2/emg/emg_process.py
  neurokit2/eog/eog_findpeaks.py
  neurokit2/eog/eog_plot.py
  neurokit2/eog/eog_process.py
  neurokit2/ppg/ppg_peaks.py
  neurokit2/ppg/ppg_plot.py
  neurokit2/ppg/ppg_process.py
  neurokit2/ppg/ppg_segment.py
  neurokit2/rsp/rsp_plot.py
  neurokit2/rsp/rsp_process.py
  neurokit2/signal/signal_fixpeaks.py
  tests/tests_ecg.py
  tests/tests_eda.py
  tests/tests_emg.py
  tests/tests_eog.py
  tests/tests_rsp.py
  tests/tests_signal_fixpeaks.py
Labels: size/XXL

#890 [Feature] ppg_peaks() now has artifact correction
  docs/examples/bio_custom/bio_custom.ipynb
  docs/examples/bio_intervalrelated/bio_intervalrelated.ipynb
  neurokit2/ecg/ecg_peaks.py
  neurokit2/ecg/ecg_plot.py
  neurokit2/ecg/ecg_segment.py
  neurokit2/ppg/ppg_peaks.py
  neurokit2/ppg/ppg_plot.py
  neurokit2/ppg/ppg_segment.py
  tests/tests_ecg.py
  tests/tests_ppg.py
  tests/tests_rsp.py
Labels: size/L
