Repository neuropsychology/NeuroKit, pull requests merged in 2023-10, with the labels that each got.

#916 [Fix] eda_plot throws ValueError when the number of onsets is not the same as the number of peaks
  neurokit2/eda/eda_plot.py
Labels: size/XS

#906 [Feature] complexity_lyapunov(): more efficient method to compute LLE
  neurokit2/complexity/complexity_decorrelation.py
  neurokit2/complexity/complexity_lyapunov.py
  neurokit2/ecg/ecg_plot.py
  neurokit2/signal/signal_autocor.py
  tests/tests_complexity.py
Labels: size/L

#917 [Fix] `SCR_Peaks_Amplitude_Mean` should be only computed on peaks
  neurokit2/eda/eda_intervalrelated.py
Labels: size/M

#920 [Feature] Add ECG peak detection by Manikandan (2012)
  neurokit2/data/read_xdf.py
  neurokit2/ecg/ecg_clean.py
  neurokit2/ecg/ecg_findpeaks.py
  neurokit2/ecg/ecg_peaks.py
Labels: size/XL
