Repository neuropsychology/NeuroKit, pull requests merged in 2023-02, with the labels that each got.

#771 Added creative commons license to documentation
  docs/conf.py
Labels: size/XS

#768 Added MSPTD ppg peak detector
  neurokit2/ppg/ppg_findpeaks.py
  tests/tests_ppg.py
Labels: size/L

#775 [Fix] fix edgecase in ecg_delineate()
  neurokit2/ecg/ecg_delineate.py
Labels: size/XS

#777 [Fix] invalid indices in ecg_delineate
  neurokit2/ecg/ecg_delineate.py
  neurokit2/ecg/ecg_segment.py
Labels: size/S

#783 [Fix] EDA peak detection and sympathetic activity
  AUTHORS.rst
  NEWS.rst
  neurokit2/ecg/ecg_segment.py
  neurokit2/eda/eda_findpeaks.py
  neurokit2/eda/eda_intervalrelated.py
  neurokit2/eda/eda_peaks.py
  neurokit2/eda/eda_sympathetic.py
  tests/tests_eda.py
Labels: size/L

#786 [Fix] sanitize RSP extrema found by scipy method
  neurokit2/rsp/rsp_amplitude.py
  neurokit2/rsp/rsp_findpeaks.py
Labels: size/XS

#787 [Fix] interpolate signal with only one value
  neurokit2/signal/signal_interpolate.py
Labels: size/XS

#789 [Feature] EDA: Add autocor index to eda_intervalrelated()
  docs/functions/eda.rst
  neurokit2/eda/eda_autocor.py
  neurokit2/eda/eda_changepoints.py
  neurokit2/eda/eda_intervalrelated.py
Labels: size/M

#785 [Feature] add respiration report with interactive plot
  neurokit2/misc/__init__.py
  neurokit2/misc/report.py
  neurokit2/ppg/ppg_plot.py
  neurokit2/ppg/ppg_process.py
  neurokit2/ppg/ppg_report.py
  neurokit2/rsp/rsp_methods.py
  neurokit2/rsp/rsp_plot.py
  neurokit2/rsp/rsp_process.py
  tests/tests_rsp.py
Labels: size/XL

#791 [Fix] Function used in rsp_methods
  neurokit2/ppg/ppg_process.py
  neurokit2/rsp/rsp_methods.py
  neurokit2/rsp/rsp_process.py
Labels: size/S
