Repository neuropsychology/NeuroKit, pull requests merged in 2023-03, with the labels that each got.

#800 [Fix] frequency-domain HRV with lombscargle given unevenly spaced data
  neurokit2/hrv/hrv_frequency.py
  neurokit2/signal/signal_psd.py
Labels: size/S

#793 [Improvement] Fixes #784 and use random generator objects rather than np.random global RNG
  neurokit2/ecg/ecg_simulate.py
  neurokit2/eda/eda_simulate.py
  neurokit2/eeg/eeg_simulate.py
  neurokit2/emg/emg_simulate.py
  neurokit2/markov/markov_simulate.py
  neurokit2/microstates/microstates_segment.py
  neurokit2/misc/__init__.py
  neurokit2/misc/random.py
  neurokit2/ppg/ppg_simulate.py
  neurokit2/rsp/rsp_simulate.py
  neurokit2/signal/signal_distort.py
  neurokit2/signal/signal_noise.py
  neurokit2/signal/signal_simulate.py
  neurokit2/signal/signal_surrogate.py
  neurokit2/stats/cluster.py
  neurokit2/stats/cluster_quality.py
  tests/tests_hrv.py
  tests/tests_ppg.py
  tests/tests_rsp.py
  tests/tests_signal.py
  tests/tests_stats.py
Labels: size/XL

#792 [Feature] add EDA report with interactive plot
  neurokit2/eda/eda_clean.py
  neurokit2/eda/eda_methods.py
  neurokit2/eda/eda_phasic.py
  neurokit2/eda/eda_plot.py
  neurokit2/eda/eda_process.py
  neurokit2/misc/report.py
  neurokit2/ppg/ppg_clean.py
  neurokit2/ppg/ppg_methods.py
  neurokit2/ppg/ppg_process.py
  neurokit2/rsp/rsp_clean.py
  neurokit2/rsp/rsp_methods.py
  neurokit2/rsp/rsp_process.py
  tests/tests_eda.py
Labels: size/XL

#811 [Feature] Add Angular Entropy (AngEn) that can be used to get comEDA
  docs/installation.rst
  neurokit2/complexity/__init__.py
  neurokit2/complexity/entropy_angular.py
  neurokit2/complexity/entropy_differential.py
  neurokit2/complexity/entropy_sample.py
Labels: size/L
