Repository neuropsychology/NeuroKit, pull requests merged in 2024-03, with the labels that each got.

#967 Update ecg_hrv.ipynb
  docs/examples/ecg_hrv/ecg_hrv.ipynb
Labels: size/XS

#960 [FIX] rr xcorr arange steps don't match
  neurokit2/rsp/rsp_rate.py
Labels: size/XS

#966 sparsEDA integration
  neurokit2/eda/eda_phasic.py
  pyproject.toml
  tests/tests_eda.py
Labels: size/M

#974 [Fix] adding sampling rate parameter to eda_intervalrelated method
  neurokit2/eda/eda_analyze.py
Labels: size/XS

#975 [Fix] read_acqknowledge now also imports duplicated channel names
  neurokit2/data/read_acqknowledge.py
Labels: size/M

#973 [Fix] refactor ecg_findpeaks
  neurokit2/ecg/ecg_findpeaks.py
  tests/ecg_data/expected_ecg_findpeaks_hamilton_bad_500.csv
  tests/ecg_data/expected_ecg_findpeaks_hamilton_good_4000.csv
  tests/tests_ecg_findpeaks.py
Labels: size/L
