Repository neuropsychology/NeuroKit, pull requests merged in 2024-05, with the labels that each got.

#989 [Feature] Test for stats/correlation.py
  neurokit2/signal/signal_power.py
  tests/tests_stats.py
Labels: size/M

#991 [Fix] Syntax to get colormap
  docs/conf.py
  neurokit2/complexity/entropy_phase.py
  neurokit2/events/events_plot.py
  neurokit2/hrv/hrv_nonlinear.py
  neurokit2/microstates/microstates_plot.py
  neurokit2/signal/signal_power.py
Labels: size/S

#987 [feature] added PPG quality assessment functionality
  neurokit2/misc/report.py
  neurokit2/ppg/__init__.py
  neurokit2/ppg/ppg_methods.py
  neurokit2/ppg/ppg_peaks.py
  neurokit2/ppg/ppg_plot.py
  neurokit2/ppg/ppg_process.py
  neurokit2/ppg/ppg_quality.py
Labels: size/L

#982 0.2.9
  .github/workflows/releasePR.yml
  README.rst
  docs/conf.py
  neurokit2/__init__.py
  neurokit2/complexity/entropy_phase.py
  neurokit2/events/events_plot.py
  neurokit2/hrv/hrv_nonlinear.py
  neurokit2/microstates/microstates_plot.py
  neurokit2/misc/report.py
  neurokit2/ppg/__init__.py
  neurokit2/ppg/ppg_methods.py
  neurokit2/ppg/ppg_peaks.py
  neurokit2/ppg/ppg_plot.py
  neurokit2/ppg/ppg_process.py
  neurokit2/ppg/ppg_quality.py
  neurokit2/signal/signal_power.py
  tests/tests_eda.py
  tests/tests_stats.py
Labels: size/L

#993 [Docs] fix location of misplaced double quotes in docstring of ecg_quality.py
  neurokit2/ecg/ecg_quality.py
Labels: size/XS
