Repository neuropsychology/NeuroKit, pull requests merged in 2024-07, with the labels that each got.

#1004 [Docs] typo in ecg_quality docstring
  neurokit2/ecg/ecg_quality.py
Labels: size/XS

#1007 [Fix] Return an empty array rather than throwing an exception if no QRS dat…
  neurokit2/ecg/ecg_findpeaks.py
  tests/tests_ecg_findpeaks.py
Labels: size/M

#1010 [Fix] Documentation Image Dependency
  .github/workflows/docs-build.yml
Labels: size/XS

#1011 [Fix] findpeaks neurokit index error
  neurokit2/ecg/ecg_findpeaks.py
  tests/tests_ecg_findpeaks.py
Labels: size/XS

#1013 [Docs] Revise definition of pNN50 and pNN20
  neurokit2/hrv/hrv_time.py
Labels: size/S

#1014 [Fix] All docs-build warnings and errors
  .github/workflows/docs-check.yml
  AUTHORS.rst
  docs/conf.py
  docs/examples/eeg_microstates/eeg_microstates.ipynb
  docs/make.bat
  neurokit2/eda/eda_intervalrelated.py
  neurokit2/eeg/mne_to_df.py
  neurokit2/events/events_find.py
  neurokit2/misc/progress_bar.py
  neurokit2/rsp/rsp_process.py
  neurokit2/signal/signal_detrend.py
  neurokit2/signal/signal_interpolate.py
  studies/complexity_eeg/README.md
  studies/ecg_benchmark/README.md
  studies/eog_blinktemplate/README.md
Labels: size/L

#1016 [Fix] GUDB name consistency
  data/gudb/download_gudb.py
Labels: size/XS
