Repository neuropsychology/NeuroKit, pull requests merged in 2024-08, with the labels that each got.

#1018 [Feature] PPG peak detection: Add MSPTDfast algorithm (Charlton et al., 2024)
  neurokit2/ppg/ppg_findpeaks.py
Labels: size/L

#1020 [Docs] Add info about NK ECG peak detection method
  neurokit2/ecg/ecg_peaks.py
Labels: size/XS

#1017 [Feature] Codebook Generation from Documentation
  docs/_static/neurokit_codebook.csv
  docs/codebook.rst
  docs/conf.py
  docs/directives/csv_codebook_directive.py
  docs/index.rst
  neurokit2/ecg/ecg_eventrelated.py
  neurokit2/ecg/ecg_intervalrelated.py
  neurokit2/ecg/ecg_process.py
  neurokit2/eda/eda_eventrelated.py
  neurokit2/eda/eda_intervalrelated.py
  neurokit2/eda/eda_process.py
  neurokit2/eda/eda_sympathetic.py
  neurokit2/emg/emg_eventrelated.py
  neurokit2/emg/emg_intervalrelated.py
  neurokit2/emg/emg_process.py
  neurokit2/eog/eog_eventrelated.py
  neurokit2/eog/eog_intervalrelated.py
  neurokit2/eog/eog_process.py
  neurokit2/hrv/hrv_frequency.py
  neurokit2/hrv/hrv_nonlinear.py
  neurokit2/hrv/hrv_rsa.py
  neurokit2/ppg/ppg_eventrelated.py
  neurokit2/ppg/ppg_intervalrelated.py
  neurokit2/ppg/ppg_process.py
  neurokit2/rsp/rsp_eventrelated.py
  neurokit2/rsp/rsp_intervalrelated.py
  neurokit2/rsp/rsp_process.py
  neurokit2/rsp/rsp_rrv.py
Labels: size/XL

#1021 [Fix] Prevent `sparseda` method from raising `AttributeError`
  neurokit2/eda/eda_phasic.py
Labels: size/XS

#992 0.2.10
  .github/workflows/docs-build.yml
  .github/workflows/docs-check.yml
  AUTHORS.rst
  data/gudb/download_gudb.py
  data/ludb/download_ludb.py
  docs/_static/neurokit_codebook.csv
  docs/codebook.rst
  docs/conf.py
  docs/directives/csv_codebook_directive.py
  docs/examples/eeg_microstates/eeg_microstates.ipynb
  docs/index.rst
  docs/make.bat
  neurokit2/__init__.py
  neurokit2/ecg/ecg_eventrelated.py
  neurokit2/ecg/ecg_findpeaks.py
  neurokit2/ecg/ecg_intervalrelated.py
  neurokit2/ecg/ecg_peaks.py
  neurokit2/ecg/ecg_process.py
  neurokit2/ecg/ecg_quality.py
  neurokit2/eda/eda_eventrelated.py
  neurokit2/eda/eda_intervalrelated.py
  neurokit2/eda/eda_phasic.py
  neurokit2/eda/eda_process.py
  neurokit2/eda/eda_sympathetic.py
  neurokit2/eeg/mne_to_df.py
  neurokit2/emg/emg_eventrelated.py
  neurokit2/emg/emg_intervalrelated.py
  neurokit2/emg/emg_process.py
  neurokit2/eog/eog_eventrelated.py
  neurokit2/eog/eog_intervalrelated.py
  neurokit2/eog/eog_process.py
  neurokit2/events/events_find.py
  neurokit2/hrv/hrv_frequency.py
  neurokit2/hrv/hrv_nonlinear.py
  neurokit2/hrv/hrv_rsa.py
  neurokit2/hrv/hrv_time.py
  neurokit2/misc/progress_bar.py
  neurokit2/ppg/ppg_eventrelated.py
  neurokit2/ppg/ppg_findpeaks.py
  neurokit2/ppg/ppg_intervalrelated.py
  neurokit2/ppg/ppg_process.py
  neurokit2/rsp/rsp_eventrelated.py
  neurokit2/rsp/rsp_intervalrelated.py
  neurokit2/rsp/rsp_process.py
  neurokit2/rsp/rsp_rrv.py
  neurokit2/signal/signal_detrend.py
  neurokit2/signal/signal_filter.py
  neurokit2/signal/signal_interpolate.py
  studies/complexity_eeg/README.md
  studies/ecg_benchmark/README.md
  studies/eog_blinktemplate/README.md
  tests/tests_ecg_findpeaks.py
Labels: size/XXL
