Repository neuropsychology/NeuroKit, pull requests merged in 2025-07, with the labels that each got.

#1117 [Feature] Allow `read_xdf` to read from URLs, and some typing/documentation improvements
  neurokit2/data/read_xdf.py
Labels: size/M

#1114 [Fix] Fixed dead links
  docs/resources/resources.rst
Labels: size/XS

#1111 [Feature] Add new signal quality method for ECG and PPG
  neurokit2/ecg/ecg_quality.py
  neurokit2/ppg/ppg_process.py
  neurokit2/ppg/ppg_quality.py
  neurokit2/signal/__init__.py
  neurokit2/signal/signal_cyclesegment.py
  neurokit2/signal/signal_quality.py
Labels: size/L
